import sharp from 'sharp';
import { mkdir } from 'node:fs/promises';
const root = 'public';
const targets = {
    'github-01-repository-main.png': { label: '저장소 이름과 main 확인', box: [.12, .18, .48, .30], markers: [[.19, .24, '1']] }, 'github-02-code-button.png': { label: 'Code / Clone 주소', box: [.56, .18, .95, .46], markers: [[.75, .24, '1'], [.76, .39, '2']] }, 'github-03-issues-tab.png': { label: 'Issues 탭', box: [.08, .13, .29, .23], markers: [[.19, .18, '1']] }, 'github-04-new-issue.png': { label: '제목과 설명 입력', box: [.16, .22, .84, .62], markers: [[.25, .28, '1'], [.28, .47, '2'], [.75, .78, '3']] }, 'github-05-issue-created.png': { label: '생성된 Issue 확인', box: [.15, .18, .85, .52], markers: [[.28, .26, '1']] }, 'github-05-pull-requests-tab.png': { label: 'Compare & pull request', box: [.19, .20, .84, .36], markers: [[.58, .27, '1'], [.74, .29, '2']] }, 'github-06-branches.png': { label: '새 브랜치 만들기', box: [.73, .15, .98, .28], markers: [[.86, .22, '1']] }, 'github-06-new-pull-request.png': { label: 'base main / compare 작업 브랜치', box: [.14, .20, .85, .44], markers: [[.31, .29, '1'], [.65, .29, '2'], [.55, .60, '3']] }, 'github-07-base-compare.png': { label: '작업 브랜치 상태', box: [.12, .17, .48, .30], markers: [[.24, .23, '1']] }, 'github-08-file-edit.png': { label: '파일명과 내용 입력', box: [.12, .20, .84, .66], markers: [[.32, .28, '1'], [.46, .52, '2']] }, 'github-09-pr-conversation.png': { label: 'PR 설명과 병합 상태', box: [.14, .20, .84, .60], markers: [[.35, .28, '1'], [.56, .47, '2']] }, 'github-10-files-changed.png': { label: 'Files changed에서 변경 확인', box: [.14, .30, .88, .78], markers: [[.42, .25, '1'], [.45, .62, '2']] }, 'github-11-review-changes.png': { label: 'Comment / Approve / Request changes', box: [.22, .23, .78, .73], markers: [[.48, .34, '1'], [.45, .55, '2'], [.45, .67, '3']] }, 'github-12-merge.png': { label: 'Merge pull request', box: [.20, .33, .78, .52], markers: [[.50, .43, '1']] }, 'github-13-confirm-merge.png': { label: 'Confirm merge', box: [.22, .36, .78, .56], markers: [[.51, .45, '1']] }, 'github-14-merged.png': { label: 'Merged와 브랜치 삭제', box: [.15, .20, .85, .43], markers: [[.34, .28, '1'], [.70, .38, '2']] }
};
const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
function overlay(width, height, c) { const [x, y, w, h] = c.box.map((v, i) => i % 2 ? v * height : v * width); const r = Math.max(15, width * .022); const circles = c.markers.map(([mx, my, n]) => `<circle cx="${mx * width}" cy="${my * height}" r="${r}" fill="#e8f35f" stroke="#17382d" stroke-width="4"/><text x="${mx * width}" y="${my * height + 6}" text-anchor="middle" font-family="Arial" font-size="${Math.max(16, width * .025)}" font-weight="700" fill="#17382d">${n}</text>`).join(''); return `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="#e8f35f" fill-opacity=".14" stroke="#d8ed45" stroke-width="${Math.max(4, width * .006)}"/>${circles}<rect x="${Math.max(8, x)}" y="${Math.max(8, y - 34)}" width="${Math.min(width - x, Math.max(180, c.label.length * 15))}" height="28" rx="8" fill="#17382d"/><text x="${Math.max(16, x + 8)}" y="${Math.max(28, y - 14)}" font-family="Arial" font-size="16" font-weight="700" fill="#fff">${esc(c.label)}</text></svg>`; }
await mkdir(`${root}/annotated/github`, { recursive: true });
for (const [file, c] of Object.entries(targets)) {
    const source = `${root}/screenshots/github/${file}`;
    const out = `${root}/annotated/github/${file.replace('.png', '-annotated.png')}`;
    const image = sharp(source);
    const meta = await image.metadata();
    if (meta.width && meta.height)
        await image.composite([{ input: Buffer.from(overlay(meta.width, meta.height, c)), top: 0, left: 0 }]).png().toFile(out);
    console.log(`annotated ${file}`);
}
